---
title: "Aqui você coloca o título"
author: "Aqui você coloca o autor(s)"
abstract: "Aqui você escreve o resumo"
header-includes:
   - \usepackage[brazil]{babel}
   - \usepackage{bm}
geometry: left=1.7cm, right=1.7cm, top=3.33cm, bottom=3.2cm
output:
  bookdown::pdf_document2:
editor_options:
  chunk_output_type: console
indent: true
---



```{r setup,include=F}

options(digits=3)  #Arrendodamento
options(scipen=999)
ggplot2::theme_set(ggplot2::theme_minimal()) #Tema dos gráficos produzidos no ggplot2
knitr::opts_chunk$set(echo=F,message=F,warning=F,fig.pos = 'H',fig.align = 'center',fig.width=7.8, fig.height=4.85)
scale_fill_discrete = \(...) ggplot2::scale_fill_brewer(... , palette="Set2") #Fixa a scale do fill dos gráficos do ggplot2
library(tidyverse)
library(tidymodels)
library(probably)
class_metrics <- metric_set(accuracy, kap, precision, sensitivity, specificity)#, roc_auc)


```




```{r}
df <- read_csv("Base de dados.csv")
df <- df %>% mutate(Sex = factor(Sex, unique(Sex)), 
                    Pclass = factor(Pclass, unique(Pclass)),
                    Survived = factor(Survived, unique(Survived)))
```

```{r}
data_split <- initial_split(df, prop = 3/4)
df_train <- training(data_split)
df_test  <- testing(data_split)

recipe_titanic <- recipe(Survived ~ ., data = df_train) %>% 
  update_role(PassengerId, Name, SibSp, Parch, Ticket, Fare, Cabin, Embarked, new_role = "ID") %>% 
  step_dummy(all_nominal_predictors())
recipe_titanic1 <- recipe(Survived ~ ., data = df_train) %>% 
  update_role(PassengerId, Name, SibSp, Parch, Ticket, Fare, Cabin, Embarked, new_role = "ID")

eng_log <- logistic_reg() %>% 
  set_engine("glm")

df_work=workflow_set(list(recipe_dummies=recipe_titanic,recipe_onehot=recipe_titanic1),
                     list(logistic=eng_log),cross=T)
fit1=df_work %>% 
  extract_workflow("recipe_dummies_logistic") %>% 
  fit(data = train_data)
fit2=df_work %>% 
  extract_workflow("recipe_onehot_logistic") %>% 
  fit(data = train_data)
collect_metrics(ft1)

glance(final_fit)

fit1 %>%
  extract_fit_parsnip() %>% 
  tidy()

ft1 <- fit1 %>%  
  predict(new_data = df_test, type = "prob") %>% 
  bind_cols(df_test)

final_fit <- df_work %>% 
  extract_workflow("recipe_dummies_logistic") %>% 
  fit(data = df)
final_predict <- final_fit %>%  
  predict(new_data = df, type = "prob") %>% 
  bind_cols(df)


final_metrics <- final_predict %>%
  mutate(
    .pred = make_two_class_pred(
      estimate = .pred_0, 
      levels = levels(Survived), 
      threshold = 0.5,
    )
  ) 

#segment_pred %>%
#  count(.pred)

yardstick::metrics(final_metrics, Survived, .pred)
class_metrics(final_metrics, truth=Survived, estimate=.pred)

#fit1 %>% 
#  conf_table(0.5,"Matriz de Confusão com ponte de corte 0.5")
```




